title: Janne Halmkrona
description: > # this means to ignore newlines until "baseurl:"
  Janne Halmkrona - kitaristi, säveltäjä, tuottaja, a&r, eurorack-hörhö, nörtti
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: halmkrona

# Author Settings
author: Janne Halmkrona # add your name
author-img: profile.png # add your photo
about-author: musique non stop # add description
social-twitter: 
social-facebook: 
social-instagram: janne_halmkrona  
social-linkedin: 
social-email:

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: G-QGGTTS2ES2

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
